#!/bin/bash
clear
case "$1" in
	  start)
	   echo " [+] Iniciando Sistema "
            ;;

          update)
             curl --progress-bar -L --fail --retry 4 -O  https://raw.githubusercontent.com/dylan14567/lab_superdylanyt/master/update-configserver
             chmod +x update-configserver
             ./update-configserver
             clear
             exit
           ;;
        
	*)
	    echo $"Usage: $0 {start|update}"
	    exit 2
	    ;;
esac
setterm -foreground green
menu()
{
clear
echo -e "\n\e[93m@configserver\n"
echo -e "\n\e[5;97m   1- Información del sistema"
echo -e "\e[5;96m   2- Listar a todos los usuarios"
echo -e "\e[5;94m   3- Añadir un Nuevo Usuario"
echo -e "\e[5;95m   4- Verificar Inicio de Sesión Actual"
echo -e "\e[5;93m   5- Verificar Último Inicio de Sesión"
echo -e "\e[5;92m   6- Comprobar los procesos del CPU"
echo -e "\e[5;97m   7- Comprobar los procesos del CPU con strace"
echo -e "\e[5;96m   8- Verificar procesos del sistema"
echo -e "\e[5;94m   9- Destruir proceso del sistema"
echo -e "\e[5;95m   10- Verificar Tráfico de Red"
echo -e "\e[5;93m   11- Verificar puertos listener"
echo -e "\e[5;92m   12- Salir"
echo -e -n "\e[5;92m \n >>>  "
read res
case $res in
"1")
clear
echo -e "\e[5;36m Información del sistema"
setterm -foreground white
clear
echo -e "\e[5;36m Arquitectura de la máquina: "
setterm -foreground white
uname -m
echo -e "\e[5;36m Versión del kernel usado: "
setterm -foreground white
uname -r
echo -e "\e[5;36m Especificaciones del sistema Ubuntu: "
setterm -foreground white
lshw
echo -e "\e[5;36m Dirección IP Privada: "
setterm -foreground white
ifconfig wlan0
echo -e "\e[5;36m Dirección IP Pública: "
setterm -foreground white
curl https://wgetip.com -w "\n"
echo -e "\e[5;36m Más información del sistema: "
setterm -foreground white
inxi
echo -e "\e[5;36m Nombre de Usuario: "
setterm -foreground white
whoami
echo -e "\e[5;36m Pulsa ENTER para salir de aqui "
read ENTER
setterm -foreground white
clear
echo -e "\e[5;36m [+] FINALIZADO "
clear
echo -e "\e[5;96m Regresar al menu s/n?"
read s
if [ "$s" = "s" ]; then 
menu
else
echo "saliendo.."
exit
fi
;;
"2")
clear
echo -e "\e[5;36m [+] Listando a todos los usuarios "
setterm -foreground white
awk -F: '{ print $1}' /etc/passwd
echo -e "\e[5;36m Pulsa ENTER para salir de aqui "
read ENTER
setterm -foreground white
clear
echo -e "\e[5;36m [+] FINALIZADO "
clear
echo -e "\e[5;96m Regresar al menu s/n?"
read s
if [ "$s" = "s" ]; then 
menu
else
echo "saliendo.."
exit
fi
;;
"3")
clear
echo -e "\e[5;36m [+] Creando Usuario "
setterm -foreground white
read -p " Escribe el nombre de Usuario: " name
adduser $name
clear
echo -e "\e[5;36m [+] FINALIZADO "
clear
echo -e "\e[5;96m Regresar al menu s/n?"
read s
if [ "$s" = "s" ]; then 
menu
else
echo "saliendo.."
exit
fi
;;
"4")
clear
echo -e "\e[5;36m [+] Verificando Inicio de Sesión Actual "
setterm -foreground white
w
echo -e "\e[5;36m Pulsa ENTER para salir de aqui "
read ENTER
setterm -foreground white
clear
echo -e "\e[5;96m Regresar al menu s/n?"
read s
if [ "$s" = "s" ]; then 
menu
else
echo "saliendo.."
exit
fi
;;
"5")
clear
echo -e "\e[5;36m [+] Verificando Último Inicio de Sesión "
setterm -foreground white
last
echo -e "\e[5;36m Pulsa ENTER para salir de aqui "
read ENTER
setterm -foreground white
clear
echo -e "\e[5;96m Regresar al menu s/n?"
read s
if [ "$s" = "s" ]; then 
menu
else
echo "saliendo.."
exit
fi
;;
"6")
clear
echo -e "\e[5;36m [+] Comprobar los procesos del CPU "
setterm -foreground white
top
clear
echo -e "\e[5;96m Regresar al menu s/n?"
read s
if [ "$s" = "s" ]; then 
menu
else
echo "saliendo.."
exit
fi
;;
"7")
clear
echo -e "\e[5;36m [+] Comprobar los procesos del CPU "
setterm -foreground white
read -p " Escribe el <PID Number>: " numero
strace -d -p $numero
echo -e "\e[5;36m Pulsa ENTER para salir de aqui "
read ENTER
setterm -foreground white
clear
echo -e "\e[5;96m Regresar al menu s/n?"
read s
if [ "$s" = "s" ]; then 
menu
else
echo "saliendo.."
exit
fi
;;
"8")
clear
echo -e "\e[5;36m [+] Verificando procesos del sistema "
setterm -foreground white
ps auxf
echo -e "\e[5;36m Pulsa ENTER para salir de aqui "
read ENTER
setterm -foreground white
clear
echo -e "\e[5;96m Regresar al menu s/n?"
read s
if [ "$s" = "s" ]; then 
menu
else
echo "saliendo.."
exit
fi
;;
"9")
clear
echo -e "\e[5;36m [+] Destruir proceso del sistema "
setterm -foreground white
read -p " ESCRIBE EL PIP: " numero
kill -9 $numero
echo -e "\e[5;36m Pulsa ENTER para salir de aqui "
read ENTER
setterm -foreground white
clear
echo -e "\e[5;96m Regresar al menu s/n?"
read s
if [ "$s" = "s" ]; then 
menu
else
echo "saliendo.."
exit
fi
;;
"10")
clear
echo -e "\e[5;36m [+] Verificando Tráfico de Red "
setterm -foreground white
iftop
echo -e "\e[5;36m Pulsa ENTER para salir de aqui "
read ENTER
setterm -foreground white
clear
echo -e "\e[5;96m Regresar al menu s/n?"
read s
if [ "$s" = "s" ]; then 
menu
else
echo "saliendo.."
exit
fi
;;
"11")
clear
echo -e "\e[5;36m [+] Verificando Puertos Listener "
setterm -foreground white
netstat -plunt
echo -e "\e[5;36m Pulsa ENTER para salir de aqui "
read ENTER
setterm -foreground white
clear
echo -e "\e[5;96m Regresar al menu s/n?"
read s
if [ "$s" = "s" ]; then 
menu
else
echo "saliendo.."
exit
fi
;;
"12")
clear
echo " [+] Saliendo..... "
echo " [+] Bye :D "
clear
exit
;;
esac
}
menu
