#!/bin/sh
clear
echo -e "\n\e[5;96m [+] Instalando lab_superdylanyt "
if [ -d $HOME ]; then
  home=$HOME
else
  home="~/"
fi

cd $home

if [ -d /data/data/com.termux/files/usr/bin ]; then
  bin="/data/data/com.termux/files/usr/bin"
elif [ -d /usr/local/bin ]; then
  bin="/usr/local/bin"
elif [ -d /bin ]; then
  bin="/bin"
elif [ -d /sbin ]; then
  bin="/sbin"
fi

if [ -e /usr/lib/sudo ]; then
  sudo="sudo"
elif [ -e /usr/bin/sudo ]; then
  sudo="sudo"
elif [ -e /usr/sbin/sudo ]; then
  sudo="sudo"
elif [ -e /lib/sudo ]; then
  sudo="sudo"
elif [ -e /bin/sudo ]; then
  sudo="sudo"
elif [ -e /sbin/sudo ]; then
  sudo="sudo"
elif [ -e /data/data/com.termux/files/usr/bin/sudo ]; then
  sudo="sudo"
else
  sudo=""
fi

if [ -e /bin/apt ]; then
  pac="apt-get"
  system="linux"
elif [ -e /bin/apt-get ]; then
  pac="apt-get"
  system="linux"
elif [ -e /usr/bin/apt-get ]; then
  pac="apt-get"
  system="linux"
elif [ -e /sbin/apt-get ]; then
  pac="apt-get"
  system="linux"
elif [ -e /usr/sbin/apt-get ]; then
  pac="apt-get"
  system="linux"
elif [ -e /bin/apk ]; then
  pac="apk"
  system="linux"
elif [ -e /usr/bin/apk ]; then
  pac="apk"
  system="linux"
elif [ -e /sbin/apk ]; then
  pac="apk"
  system="linux"
elif [ -e /usr/sbin/apk ]; then
  pac="apk"
  system="linux"
elif [ -e /bin/yum ]; then
  pac="yum"
  system="fedora"
elif [ -e /usr/bin/yum ]; then
  pac="yum"
  system="fedora"
elif [ -e /sbin/yum ]; then
  pac="yum"
  system="fedora"
elif [ -e /usr/sbin/yum ]; then
  pac="yum"
  system="fedora"
elif [ -e /usr/local/bin/brew ]; then
  pac="brew"
  system="mac"
  sudo=""
elif [ -e /data/data/com.termux/files/usr/bin/pkg ]; then
  pac="pkg"
  system="termux"
elif [ -e /data/data/com.termux/files/usr/bin/apt ]; then
  pac="apt"
  system="termux"
elif [ -e /data/data/com.termux/files/usr/bin/apt-get ]; then
  pac="apt-get"
  system="termux"
fi

if [ ! -e $bin/wget ]; then
  if [ $sudo ]; then
    $sudo $pac install wget -y
  else
    $pac install wget -y
  fi
fi
if [ ! -e $bin/curl ]; then
  if [ $sudo ]; then
    $sudo $pac install curl -y
  else
    $pac install curl -y
  fi
fi

if [ ! -e $bin/wget ]; then
  if [ $sudo ]; then
    $sudo wget -c --quiet --show-progress https://raw.githubusercontent.com/dylan14567/lab_superdylanyt/master/lab_superdylanyt
  else
    wget -c --quiet --show-progress https://raw.githubusercontent.com/dylan14567/lab_superdylanyt/master/lab_superdylanyt
  fi
fi

if [ -e lab_superdylanyt ]; then
    if [ $sudo ]; then
      $sudo mv -v lab_superdylanyt $bin
      $sudo chmod +x $bin/lab_superdylanyt
    else
      mv -v lab_superdylanyt $bin
      chmod +x $bin/lab_superdylanyt
    fi
  fi

if [ -e $bin/lab_superdylanyt ]; then
    clear
    echo -e "\n\e[5;96m [+] Instalación Completada "
  else
    clear
    echo -e "\n\e[5;96m [+] Hubo un error al instalar "
  fi
fi
