#!/bin/bash
clear
rm -rf lab_superdylanyt
echo " [+] Actualizando lab_superdylanyt "
wget -c --quiet --show-progress https://raw.githubusercontent.com/dylan14567/lab_superdylanyt/master/lab_superdylanyt
chmod +x lab_superdylanyt
clear
echo " [+] Actualización Completada "
clear
rm -rf update-lab_superdylanyt
             
