#!/bin/bash
clear
rm -rf lab_superdylanyt
echo " [+] Actualizando lab_tool "
curl --progress-bar -L --fail --retry 4 -O  https://raw.githubusercontent.com/dylan14567/lab_superdylanyt/master/lab_tool
chmod +x lab_tool
clear
echo " [+] Actualización Completada "
clear
rm -rf update-lab_tool
             
