blank_issues_enabled: false
contact_links:
  - name: SUPERDYLANYT Community Support
    url: https://dylan14567.github.io/Laboratorio-SUPERDYLANYT/contacto
    about: Please ask and answer questions here.
  - name: GitHub Security Bug Bounty
    url: https://github.com/dylan14567/lab_superdylanyt/blob/master/.github/ISSUE_TEMPLATE/bug_report.md
    about: Please report security vulnerabilities here.
